# Use postgres/example user/password credentials
#docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
#The default postgres user and database are created in the entrypoint with initdb.
#docker run -it --rm --network some-network postgres psql -h some-postgres -U postgres
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 9099:9099